---
name: hyprland-atomic-gaming
description: Fedora Atomic with Hyprland (Gaming PC)
base-image: ghcr.io/blue-build/base-images/fedora-base
image-version: latest
modules:
  - type: kargs
    kargs:
    - amdgpu.ppfeaturemask=0xffffffff
  - type: dnf
    repos:
      nonfree: rpmfusion
  - type: files
    files:
      - source: system
        destination: /
  - type: brew
    nofile-limits: true
    brew-analytics: false
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - SourceCodePro
  - type: rpm-ostree 
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/lizardbyte/beta/repo/fedora-%OS_VERSION%/lizardbyte-beta-fedora-%OS_VERSION%.repo
      - vscode.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      - https://packages.microsoft.com/keys/microsoft.asc
    install:
      # Hyprland Packages
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprshot
      - rofi-wayland
      - uwsm
      - waybar
      - wlogout
      - xdg-desktop-portal-hyprland
      # Desktop packages
      - bat
      - blueman
      - brave-browser
      - btop
      - code
      - containerd
      - docker-cli
      - docker-compose
      - docker-compose-switch
      - discord
      - firewall-config
      - firefox
      - foot
      - fzf
      - gcc
      - gnome-text-editor
      - gvfs
      - input-remapper
      - kitty
      - libratbag-ratbagd
      - libva
      - libva-intel-media-driver
      - libva-nvidia-driver
      - loupe
      - man-pages
      - mc
      - neovim
      - NetworkManager
      - NetworkManager-tui
      - nwg-displays
      - nwg-look
      - papers
      - pavucontrol
      - podman
      - podman-tui
      - qalculate-gtk
      - ripgrep
      - speedtest-cli
      - Sunshine
      - SwayNotificationCenter
      - tealdeer
      - thunderbird
      - thunar
      - thunar-volman
      - thunar-archive-plugin
      - thunar-vcs-plugin
      - thunar-media-tags-plugin
      - tmux
      - tree-sitter-cli
      - tumbler
      - unrar
      - vulkan-tools
      - wireguard-tools
      - wl-clipboard
      - xfconf
      - xhost
      - zsh
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - com.github.iwalton3.jellyfin-media-player
          - com.moonlight_stream.Moonlight
          - com.slack.Slack
          - com.stremio.Stremio
          - org.localsend.localsend_app
          - io.github.radiolamp.mangojuice
          - io.github.benjamimgois.goverlay
          - com.vysp3r.ProtonPlus
          - com.termius.Termius
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - io.github.ilya_zlobintsev.LACT
          - org.openrgb.OpenRGB
          - org.onlyoffice.desktopeditors
  - type: systemd
    system:
      enabled:
        - docker.service
        - ratbagd.service
        - sshd.service
    user:
      enabled:
        - sunshine.service
  - type: signing
